// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5A-3Ebwn2YCe9ukpwGam0tFsA5zIEkJ4',
    appId: '1:351433578987:web:55d9dfa6fb93bbfe3ca1ae',
    messagingSenderId: '351433578987',
    projectId: 'fbla-app-72e34',
    authDomain: 'fbla-app-72e34.firebaseapp.com',
    storageBucket: 'fbla-app-72e34.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKjpal0pwKKn_1LdB76TZKmveul7l9h4',
    appId: '1:351433578987:android:be9bf5d009b977a23ca1ae',
    messagingSenderId: '351433578987',
    projectId: 'fbla-app-72e34',
    authDomain: 'fbla-app-72e34.firebaseapp.com',
    storageBucket: 'fbla-app-72e34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6IftZV1lte6WuHVxNVJtmFT9YD3pGngg',
    appId: '1:351433578987:ios:3529c979225f1d763ca1ae',
    messagingSenderId: '351433578987',
    projectId: 'fbla-app-72e34',
    storageBucket: 'fbla-app-72e34.firebasestorage.app',
    iosBundleId: 'com.meghm.fblaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6IftZV1lte6WuHVxNVJtmFT9YD3pGngg',
    appId: '1:351433578987:ios:3529c979225f1d763ca1ae',
    messagingSenderId: '351433578987',
    projectId: 'fbla-app-72e34',
    storageBucket: 'fbla-app-72e34.firebasestorage.app',
    iosBundleId: 'com.meghm.fblaapp',
  );
}
