name: Build & Upload iOS (signed .ipa)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: macos-latest
    env:
      FLUTTER_CHANNEL: stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import signing certificate and provisioning profile
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-base64: ${{ secrets.IOS_SIGNING_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_SIGNING_P12_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: |
          pod install --repo-update

      - name: Build signed ipa
        run: |
          flutter build ipa --export-method app-store

      - name: Upload to App Store Connect (altool)
        if: ${{ secrets.APPLE_ID && secrets.APP_SPECIFIC_PASSWORD }}
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APP_SPECIFIC_PASSWORD: ${{ secrets.APP_SPECIFIC_PASSWORD }}
        run: |
          set -e
          IPA_PATH=$(ls build/ios/ipa/*.ipa | head -n 1)
          echo "Uploading $IPA_PATH to App Store Connect..."
          xcrun altool --upload-app -f "$IPA_PATH" -u "$APPLE_ID" -p "$APP_SPECIFIC_PASSWORD" --type ios --output-format xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-artifacts
          path: |
            build/ios/ipa/*.ipa
            build/ios/ipa/*.xcarchive


# Secrets required for this workflow:
# - IOS_SIGNING_P12_BASE64 : base64-encoded P12 certificate (includes private key).
# - IOS_SIGNING_P12_PASSWORD : password for the P12 file.
# - IOS_PROVISIONING_PROFILE_BASE64 : base64-encoded provisioning profile (.mobileprovision).
# - APPLE_ID : (optional) Apple ID email used to upload.
# - APP_SPECIFIC_PASSWORD : (optional) App-specific password for the Apple ID (create at appleid.apple.com).
